stages:
  - build
  - publish
#  - test

build:
  stage: build
  script: ./build_prod.sh
  tags:
    - gtk
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    - doc/doxygen/
    - build/WineGUI-*.deb
    - build/WineGUI-*.rpm
    - build/WineGUI-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build/bin
      policy: push

publish:
  stage: publish
  tags:
    - gtk
  only:
    - master
  script:
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no ./build/WineGUI-v* melroy@server.melroy.org:/var/www/winegui.melroy.org/html/downloads
    - export APP_VERSION=`./build/bin/winegui --version`
    - echo $APP_VERSION
    - ./create_release_links.sh
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build/bin
      policy: pull

#test:
#  stage: test
#  script: ./build/bin/runTests
#  tags:
#    - gtk
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build/bin/