stages:
  - test
  - build
  - publish

static_code_analysis:
  stage: test
  tags:
    - gtk
  script: cppcheck --enable=all --suppressions-list=suppressions.txt --error-exitcode=1 -I ./include/ ./src/

build:
  stage: build
  tags:
    - gtk
  script: ./build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    - doc/doxygen/
    - build/WineGUI-*.deb
    - build/WineGUI-*.rpm
    - build/WineGUI-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build/bin
      policy: push

publish:
  stage: publish
  tags:
    - gtk
  only:
    - tags
  except:
    - branches
  script:
    - export APP_VERSION=`./build/bin/winegui --version`
    - echo $APP_VERSION
    - ./release.sh
    - ./create_release_links.sh
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build/bin
      policy: pull

#unit_test:
#  stage: test
#  script: ./build/bin/runTests
#  tags:
#    - gtk
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build/bin/
