image: danger89/gtk3-docker-cmake-ninja:3.3

stages:
  - test
  - build
  - release

static_code_analysis:
  stage: test
  script:
    - cppcheck --version
    - ./scripts/cpp_check.sh

code_style_guidelines:
  stage: test
  script:
    - clang-format --version
    - ./scripts/check_format.sh

# Build WineGUI + Doxygen
test-build:
  stage: build
  rules:
    - if: "$CI_COMMIT_TAG == null"
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 month
    paths:
      - doc/doxygen/
      - build_prod/WineGUI-*.deb
      - build_prod/WineGUI-*.rpm
      - build_prod/WineGUI-*.tar.gz

# Build Prd & Deploy new release (deployment job)
build-and-deploy:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "melroy" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - ./scripts/build_prod.sh
    - export APP_VERSION=${CI_COMMIT_TAG}
    - ./scripts/create_latest_release_file.sh
  environment:
    name: production
    url: https://winegui.melroy.org/downloads
  artifacts:
    name: "Packages + Documentation"
    expire_in: 3 months
    paths:
      - doc/doxygen/
      - release/
      - build_prod/WineGUI-*.deb
      - build_prod/WineGUI-*.rpm
      - build_prod/WineGUI-*.tar.gz

# Create release links
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  # Let's test this step now
  #rules:
  #  - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "melroy" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - export TAG_NAME=${CI_COMMIT_TAG}
    - >
      release-cli 
      --job-token ${CI_JOB_TOKEN}
      --project-id ${CI_PROJECT_ID}
      update 
      --tag-name 'v1.9.1'
      --assets-link '[{"name":"Asset1","url":"https://example.com/some/location/1","link_type":"other","filepath":"xzy"}, {"name":"Asset2","url":"https://example.com/some/location/2"}]'

#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
