image: danger89/gtk3-docker-cmake-ninja:3.3

stages:
  - test
  - build
  - release

static_code_analysis:
  stage: test
  script:
    - cppcheck --version
    - ./scripts/cpp_check.sh

code_style_guidelines:
  stage: test
  script:
    - clang-format --version
    - ./scripts/check_format.sh

# Build WineGUI + Doxygen
test-build:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG == null && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 month
    paths:
      - doc/doxygen/
      - build_prod/WineGUI-*.deb
      - build_prod/WineGUI-*.rpm
      - build_prod/WineGUI-*.tar.gz
  # TODO: Do we really need this cache path still??
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build_prod/bin
    policy: push

build-and-deploy:
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "melroy" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script: ./scripts/build_prod.sh
  environment:
    name: production
    url: https://winegui.melroy.org/downloads  
  artifacts:
    name: "Packages + Documentation"
    expire_in: 3 months
    paths:
      - doc/doxygen/
      - build_prod/WineGUI-*.deb
      - build_prod/WineGUI-*.rpm
      - build_prod/WineGUI-*.tar.gz
  # TODO: Do we really need this cache path still??
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build_prod/bin
    policy: push

# Upload the artifacts / release
release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == "melroy" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - export APP_VERSION=${CI_COMMIT_TAG}
    # TODO: Update upload scripts & create script, we don't have access anymore from Docker runner
    - ./scripts/upload_release.sh
    - ./scripts/create_latest_release_file.sh
    - ./scripts/create_release_links.sh
  cache:
    key: "$CI_PIPELINE_ID"
    paths:
      - build_prod/bin
    policy: pull

#unit_test:
#  stage: test
#  script: ./build_prod/bin/runTests
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build_prod/bin/
