stages:
  - build
#  - test

build:
  stage: build
  script: ./build.sh
  tags:
    - gtk
  artifacts:
    name: "Documentation"
    expire_in: 1 week
    paths:
    - doc/doxygen/
  cache:
      key: "$CI_PIPELINE_ID"
      policy: push
      paths:
        - build/bin/

#test:
#  stage: test
#  script: ./build/bin/runTests
#  tags:
#    - gtk
#  cache:
#      key: "$CI_PIPELINE_ID"
#      policy: pull
#      paths:
#        - build/bin/